spring.application.name=BankSurvay
spring.datasource.url=jdbc:mysql://localhost:3306/bank_survey
spring.datasource.username=root
spring.datasource.password=sql1_mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true